Sample develop
Zbigniew-Jedlinski-Mobica/Vulkan-Samples-Patch-Control-Points pull request #1
Opened 2023-03-20 12:22 UTC by Zbigniew-Jedlinski-Mobica

## Description

Please include a summary of the change, new sample or fixed issue. Please also include relevant motivation and context.
Please read the [contribution guidelines](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md)

Fixes #<issue number>

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

2023-03-20 14:45 UTC, Karina-Murawko-Wisniewska-Mobica commented on samples/extensions/patch_control_points/README.md
> +
```suggestion

![Sample](./images/patch_control_point_screenshot.png)

```

2023-03-20 14:46 UTC, Karina-Murawko-Wisniewska-Mobica commented on samples/extensions/patch_control_points/README.md
> +
The screenshot link in readme is missing.

2023-03-21 07:11 UTC, Michal-Masiukiewicz-Mobica commented on shaders/patch_control_points/tess.tese
> +vec4 interpolate3D(vec4 v0, vec4 v1, vec4 v2)
Seems like only this interpolate3D function is required. Maybe remove others?

2023-03-21 07:11 UTC, Michal-Masiukiewicz-Mobica commented on shaders/patch_control_points/tess.tesc
> +	if (gl_InvocationID == 0)
Maybe some comment why (gl_InvocationID == 0) is special?
I think for somebody who doesn't know how tesselation shaders work (me) it would be helpful.

2023-03-23 11:38 UTC, Szymon-Rajczakowski-Mobica requested changes

2023-03-23 11:38 UTC, Szymon-Rajczakowski commented on samples/extensions/patch_control_points/patch_control_points.cpp
> +#include <vector>
These includes are not needed because are included indirectly by #include "patch_control_points.h"

2023-03-23 11:38 UTC, Szymon-Rajczakowski commented on samples/extensions/patch_control_points/patch_control_points.cpp
> +	title = "Extended Dynamic State2";
Change title to Patch Control Points or sth like that

2023-03-23 11:38 UTC, Szymon-Rajczakowski commented on samples/extensions/patch_control_points/patch_control_points.cpp
> +	VK_CHECK(vkCreateGraphicsPipelines(get_device().get_handle(), VK_NULL_HANDLE, 1, &graphics_create, VK_NULL_HANDLE, &pipeline.dynamically_tessellation));
why don't you use pipeline_cache here?

2023-03-23 11:38 UTC, Szymon-Rajczakowski-Mobica commented on samples/extensions/patch_control_points/patch_control_points.cpp
> +		//	dynamiclly tessellation
typo

2023-03-23 11:38 UTC, Szymon-Rajczakowski-Mobica commented on samples/extensions/patch_control_points/patch_control_points.cpp
> + * 	@brief Creating descriptor sets for 3 separate pipelines.
2 separate pipelines

2023-03-24 13:11 UTC, merged